name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR1 }}
          with:
          args: >
            -X
            -Dsonar.projectKey=payalm2_sonar1
            -Dsonar.organization=payalm2
            -Dsonar.qualitygate.wait=true
            -Dsonar.qualitygate.timeout=300

